# 2D Brunton System - State-Space Manifold Learning
system_name: "brunton_manifold"

# Training Mode: "reconstruction" or "prediction"
mode: "comparison"

# 2D Brunton System Definition: dx₁/dt = μx₁, dx₂/dt = λ(x₂ - x₁²)
dynamics:
  type: "brunton"
  parameters:
    mu: -0.05      # Parameter μ in the first equation
    lambda: -1.0   # Parameter λ in the second equation

# Initial Conditions Sampling
initial_conditions:
  bounds:
    x1: [-4.0, 4.0]
    x2: [-4.0, 4.0]
  num_samples: 500
  sampling_method: "grid"

# Trajectory Generation
trajectory:
  time_span: [0.0, 80.0]
  time_points: 500
  solver: "RK45"
  rtol: 0.00000001
  atol: 0.0000000001
  normalize: false
  remove_transient: 0

# Dataset Configuration
dataset:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  shuffle: true
  random_seed: 42

# State-Space Autoencoder (2D -> 1D manifold)
autoencoder:
  latent_dim: 3
  
  encoder:
    hidden_layers: [64, 32]
    activation: "tanh"
    dropout: 0.0
    batch_norm: false
  
  decoder:
    hidden_layers: [32, 64]
    activation: "tanh"
    dropout: 0.0
    batch_norm: false
    output_activation: "linear"
  
  # Latent dynamics network (only used in prediction mode)
  latent_dynamics:
    hidden_layers: [64, 64]
    activation: "tanh"
    dropout: 0.0

# Training Configuration
training:
  batch_size: 512
  epochs: 100
  learning_rate: 0.001
  optimizer: "adam"
  scheduler:
    type: "step"
    step_size: 40
    gamma: 0.7
  loss_function: "mse"
  early_stopping:
    patience: 20
    min_delta: 0.000001
  save_best_model: true
  
  # Prediction mode settings (only used when mode: "prediction")
  prediction:
    reconstruction_weight: 1.0  # Weight for reconstruction loss
    prediction_weight: 1.0      # Weight for prediction loss
    
    # Multi-step prediction settings
    prediction_steps: 3         # Number of future steps to predict (k=1 for single-step)
    decay_factor: 0.9          # Exponential decay factor (gamma=1.0 for single-step)

# Evaluation Configuration
evaluation:
  metrics:
    - "reconstruction_error"
    - "manifold_quality"
    - "pca_comparison"
  
  visualization:
    plot_manifold: true
    plot_reconstruction: true
    plot_trajectories: true
    save_plots: true
    plot_format: "png"
    dpi: 300

# Output Configuration
output:
  base_dir: "results"
  experiment_name: "brunton_manifold"
  save_model: true
  save_embeddings: true
  generate_report: true 