# 3D Linear System - State-Space Manifold Learning
system_name: "linear_manifold"

# 3D Linear System Definition: dy/dt = A*y
dynamics:
  type: "linear"
  parameters:
    mu: -0.05      # Parameter μ in the system matrix
    lambda: -1  # Parameter λ in the system matrix

# Initial Conditions Sampling
initial_conditions:
  bounds:
    y1: [-4.0, 4.0]
    y2: [-4.0, 4.0]
    y3: [-4.0, 4.0]
  num_samples: 500
  sampling_method: "grid"

# Trajectory Generation
trajectory:
  time_span: [0.0, 80.0]
  time_points: 500
  solver: "RK45"
  rtol: 0.00000001
  atol: 0.0000000001
  normalize: false
  remove_transient: 0

# Dataset Configuration
dataset:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  shuffle: true
  random_seed: 42

# State-Space Autoencoder (3D -> 2D manifold)
autoencoder:
  latent_dim: 2
  
  encoder:
    hidden_layers: [64, 32]
    activation: "tanh"
    dropout: 0.0
    batch_norm: false
  
  decoder:
    hidden_layers: [32, 64]
    activation: "tanh"
    dropout: 0.0
    batch_norm: false
    output_activation: "linear"

# Training Configuration
training:
  batch_size: 512
  epochs: 150
  learning_rate: 0.001
  optimizer: "adam"
  scheduler:
    type: "step"
    step_size: 40
    gamma: 0.7
  loss_function: "mse"
  early_stopping:
    patience: 20
    min_delta: 0.000001
  save_best_model: true

# Evaluation Configuration
evaluation:
  metrics:
    - "reconstruction_error"
    - "manifold_quality"
    - "pca_comparison"
  
  visualization:
    plot_manifold: true
    plot_reconstruction: true
    plot_trajectories: true
    save_plots: true
    plot_format: "png"
    dpi: 300

# Output Configuration
output:
  base_dir: "results"
  experiment_name: "linear_manifold"
  save_model: true
  save_embeddings: true
  generate_report: true 