# Lorenz System - State-Space Manifold Learning
system_name: "lorenz_manifold"

# Lorenz System Definition
dynamics:
  type: "lorenz"
  parameters:
    sigma: 10.0
    rho: 28.0
    beta: 2.667

# Initial Conditions Sampling
initial_conditions:
  bounds:
    x: [-15.0, 15.0]
    y: [-20.0, 20.0] 
    z: [5.0, 35.0]
  num_samples: 500
  sampling_method: "random"

# Trajectory Generation
trajectory:
  time_span: [0.0, 10.0]
  time_points: 500
  solver: "RK45"
  rtol: 0.00000001
  atol: 0.0000000001
  normalize: true
  remove_transient: 50

# Dataset Configuration
dataset:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  shuffle: true
  random_seed: 42

# State-Space Autoencoder (3D -> 2D manifold)
autoencoder:
  latent_dim: 2
  
  encoder:
    hidden_layers: [32, 16]
    activation: "relu"
    dropout: 0.0
    batch_norm: false
  
  decoder:
    hidden_layers: [16, 32]
    activation: "relu"
    dropout: 0.0
    batch_norm: false
    output_activation: "linear"

# Training Configuration
training:
  batch_size: 512
  epochs: 100
  learning_rate: 0.001
  optimizer: "adam"
  scheduler:
    type: "step"
    step_size: 30
    gamma: 0.5
  loss_function: "mse"
  early_stopping:
    patience: 15
    min_delta: 0.000001
  save_best_model: true

# Evaluation Configuration
evaluation:
  metrics:
    - "reconstruction_error"
    - "manifold_quality"
    - "pca_comparison"
  
  visualization:
    plot_manifold: true
    plot_reconstruction: true
    plot_trajectories: true
    save_plots: true
    plot_format: "png"
    dpi: 300

# Output Configuration
output:
  base_dir: "results"
  experiment_name: "lorenz_manifold"
  save_model: true
  save_embeddings: true
  generate_report: true 