# Lorenz System - Comprehensive Comparison with Latent Dimension Sweep
system_name: "lorenz_comparison_sweep"

# Lorenz System Definition
dynamics:
  type: "lorenz"
  parameters:
    sigma: 10.0
    rho: 28.0
    beta: 2.667

# Initial Conditions Sampling
initial_conditions:
  bounds:
    x: [-15.0, 15.0]
    y: [-20.0, 20.0] 
    z: [5.0, 35.0]
  num_samples: 500  # Reduced for testing
  sampling_method: "grid"

# Trajectory Generation
trajectory:
  time_span: [0.0, 5.0]
  time_points: 500
  solver: "RK45"
  rtol: 0.00000001
  atol: 0.0000000001
  normalize: true
  remove_transient: 0

# Dataset Configuration
dataset:
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  shuffle: true
  random_seed: 42

autoencoder:
  latent_dim: 3  # Will be overridden by sweep
  
  encoder:
    hidden_layers: [64, 32]
    activation: "relu"
    dropout: 0.0
    batch_norm: false
  
  decoder:
    hidden_layers: [32, 64]
    activation: "relu"
    dropout: 0.0
    batch_norm: false
    output_activation: "linear"
  
  latent_dynamics:
    linear: false
    monotonic: false
    hidden_layers: [64, 64]
    activation: "tanh"
    dropout: 0.0
    weight_reparam: "absolute"

training:
  batch_size: 512
  epochs: 50
  learning_rate: 0.001
  optimizer: "adam"
  scheduler:
    type: "step"
    step_size: 40
    gamma: 0.7
  early_stopping:
    patience: 20
    min_delta: 0.000001
  save_best_model: true
  
  # Brunton-style composite losses configuration
  losses:
    use_reconstruction: true      # Enable reconstruction loss
    use_prediction: true          # Enable prediction loss
    use_latent_linearity: false    # Enable latent linearity loss for better A matrix learning
    use_l_inf: false             # Enable L-infinity error loss
    use_weight_decay_regularizer: false  # Enable weight decay regularization
    alpha1: 1                   # Weight for reconstruction + prediction (increased for better training)
    alpha2: 1e-7                 # Weight for L-infinity error
    alpha3: 1e-15                # Weight for weight decay
    S_p: 10                      # Prediction steps for loss computation and data preparation
    decay_factor: 0.9            # Exponential decay factor for multi-step prediction
    l_inf_m_steps: 1             # Steps to include in L-infinity
    weight_decay_targets: [encoder, decoder, latent_dynamics]  # Modules for weight decay

evaluation:
  metrics:
    - "reconstruction_error"
    - "manifold_quality"
    - "pca_comparison"
  
  visualization:
    plot_manifold: true
    plot_reconstruction: true
    plot_trajectories: true
    save_plots: true
    plot_format: "png"
    dpi: 300

# Model configuration - defines what models to train
models:
  state_mlp:
    enabled: true
    hidden_layers: [128, 128]
    activation: "relu"
  
  latent_nn:
    enabled: true
    latent_dims: [4, 6, 8]  # Sweep over these latent dimensions
    hidden_layers: [64, 64]
    activation: "tanh"
  
  latent_monotonic:
    enabled: true
    latent_dims: [4, 6, 8]  # Sweep over these latent dimensions
    hidden_layers: [64, 64]
    activation: "tanh"
    weight_reparam: "absolute"
  
  latent_linear:
    enabled: true
    latent_dims: [4, 6, 8]  # Sweep over these latent dimensions
    # Note: Linear dynamics uses z_{k+1} = A × z_k (single matrix, no hidden layers)

output:
  base_dir: "results"
  experiment_name: "lorenz_comparison_sweep"
  save_model: true
  save_embeddings: true
  generate_report: true 